config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'photos#index'
  post 'photos/detect'
  resources :photos, only: [:new, :create, :show, :edit, :update]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
class Photo < ApplicationRecord
  mount_uploader :image, ImageUploader
  validates_integrity_of :image
  validates_processing_of :image
  validates_format_of :image, :with => %r{\.(png|jpg|jpeg)\z}i, :error => "Please use valid formats for your pictures. (JPG,PNG,JPEG)"
  #:photo_url represents the column name in the photos table, which is photo_url
  #PhotoUploader must tally with the column name

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def index
  	@photo = Photo.new
  end

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  # after_action :detect, only: [:create]
  def index 
    @photo = Photo.new
    #@photos = Photo.all
    # if params[:rid]
    #   @uploaded_photo = Photo.find(params[:rid])
    # end
  end


  def new
    @photo = Photo.new  #initialize an empty object for the form, so that we can fill in with details using the form.
    render template: "photos/new"
  end

  def create 
    @photo = Photo.new(photo_params)
    if @photo.save
      # render :json => @photo
        # respond_to do |format|
        # format.html
        # format.json { render :json => @photo}
      respond_to do |format|
        format.js
        format.html
      end
       # flash[:success] = "You uploaded your photo!"
       # redirect_to @photo
    else
      respond_to do |format|
        format.json { render json: { error: 'Failed to process' } }
        format.js { flash.now[:error] = "Please upload valid file to process. Ex: png, jpeg, jpg" }
      end
      #flash[:error] = "Something's wrong. Please try again."
      # render 'page/index'
    end
  end


  def show
    # @photo = Photo.new
    @photo = Photo.find(params[:id])
  end 

  def edit
    @photo = Photo.find(params[:id])
  end

  def update
    @photo = Photo.find(params[:id])
    @photo.update(photo_params)
    redirect_to @photo
  end


  def detect 
    @photo = Photo.find(params[:photo_id])
  	rekog = Aws::Rekognition::Client.new(region: "us-west-2")
    result = rekog.detect_labels({
      image: {
        s3_object: {
        bucket: "jasmine-rekoq",
        name: "uploads/photo/image/#{params[:photo_id]}/#{@photo.image_identifier}"
        },
      }
    })
    @photo.description = result.labels 
    @photo.save
    #if @photo.save
    #   respond_to do |format|
    #     format.js
    #     format.html
    #   end
    # else
    #   respond_to do |format|
    #     format.json { render json: { error: 'Failed to process' } }
    #   end
    # end
    # redirect_to @photo
  end 

  private
  def photo_params
  	params.require(:photo).permit(:image, description: []) 
  end 


end

app/helpers/application_helper.rb
module ApplicationHelper
	
  def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type.to_sym] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} fade in") do 
              concat content_tag(:button, 'x', class: "close", data: { dismiss: 'alert' })
              concat message 
            end)
    end
    nil
  end

end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/rekognition_helper.rb
module RekognitionHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Imageria</title>

    <%= csrf_meta_tags %>
    <!--Google Icon Font-->
    <link href="https://fonts.googleapis.com/css?family=Patrick+Hand+SC" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Bahiana|Questrial" rel="stylesheet">
    <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href='https://fonts.googleapis.com/css?family=Permanent+Marker:400' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css"> 

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div id="fb-root"></div>
    <script>(function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.9&appId=1950135798535312";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));
    </script>
  
     <div class="container">
         <%= yield %>
     </div>

  </body>
</html>

app/views/page/index.html.erb
<h2>Upload a photo!</h2>
<%= form_for @photo, html: { class: "dropzone", id: "photo-dropzone" }  do |form| %>

<div class="col-sm-12">

 <div class="fallback">
  <%= form.label :image, "Upload a photo" %>
  <%= form.file_field :image %>
</div>


</div>


<% end %>

<script type="text/javascript">
$(function() {

  var photoDropzone = new Dropzone("#photo-dropzone");
  return photoDropzone.on("success", function(file, responseText) {
    var imageUrl;
    imageUrl = responseText.image.url;
    window.location.href = ("/photos/"+responseText.id);
  });
});

  Dropzone.autoDiscover = false;

  Dropzone.options.photoDropzone = {
  	paramName: 'photo[image]',
    parallelUploads: 10,
    acceptedFiles: 'image/*',
    maxFiles: 1,      
    maxFilesize: 256,
    dictDefaultMessage: "Try dragging an image here, or click to upload.",
    addRemoveLinks: false
  };


</script>

<!--<%= form_for @photo, remote: true, html: { class: "dropzone", id: "photo-dropzone" }  do |form| %> -->

<!-- <div class="col-sm-12"> -->

<!--  <div class="fallback">
  <%= form.label :image, "Upload a photo" %>
  <%= form.file_field :image %>
</div>
 -->

<!-- </div>


<% end %>




<!-- <script type="text/javascript">
$(function() {
  var photoDropzone = new Dropzone("#photo-dropzone");
  return photoDropzone.on("success", function(file, responseText) {
    // debugger;
    // $(".dropzone").hide();
    // $.ajax({
    //   url: "http://localhost:3000/photos/" + responseText.id,
    //   data: $(this).serialize(),

    //   success: function(data) {  
    //   debugger;    
    //     $("#jumbo").append(data.image);   
    //     },   
    // });

    // $("#jumbo").append("YOLO");
    var imageUrl;
    imageUrl = responseText.image;
    var imageID = responseText.id;


        // window.location.href = ("/photos/"+responseText.id);


  });
});

  Dropzone.autoDiscover = false;

  Dropzone.options.photoDropzone = {
    paramName: 'photo[image]',
    parallelUploads: 10,
    acceptedFiles: '.jpeg,.jpg,.png',
    maxFiles: 1,      
    maxFilesize: 256,
    dictDefaultMessage: "Try dragging an image here, or click to upload.",
    addRemoveLinks: false
  };




</script>
 -->

app/views/photos/_form.html.erb
<div class="form-group has-feedback" style="margin: 2em; width: 300px;">

<div class="file-field" style="padding:10px;">
  <%= form.file_field :image, :class => "btn btn-default btn-large btn3d"%>
</div>

    <div class="submit-field" style="padding:10px 0 0 0;">
      <%= form.submit "Upload", :onclick => "move()", class: "btn btn-success btn-large btn3d"%> 
    </div>


</div>

app/views/photos/_photo.html.erb
<div class="col-sm-12 col-md-12 col-lg-12" style="text-align: center;float:center;">
  <h2>Your results are out!</h2>
      <%= image_tag photo.image.url(:thumb) if photo.image %>

      <% rekog = Aws::Rekognition::Client.new(region: "us-west-2") %>
        <% result = rekog.detect_labels({ %>
          <%  image: { %>
          <% s3_object: { %>
            <% bucket: "jasmine-rekog", %>
              <% name: "uploads/photo/image/#{photo.id}/#{photo.image_identifier}" %>
          <% }, %>
        <% } %>
        <% }) %>

      <% photo.description = result.labels %>
      <% photo.save %>

  <% if photo.description %>
    <div id="content-1" class="pmd-card pmd-card-default pmd-z-depth pmd-card-custom-form" style="padding-bottom: 50px;"><br>
      <div class="pmd-card-title">
      <h3 class="pmd-card-title-text">Image results:</h3>
	    <% photo.description.each do |label| %><br>
      <div class="pmd-card-body">
        <!-- <p><%= label["name"] %> <%= label["confidence"].to_i %>%</p> -->
          <div class="progress">
            <div class="progress-bar progress-bar-success progress-striped active" role="progressbar" aria-valuenow="<%= label["confidence"].to_i %>" aria-valuemin="0" aria-valuemax="100">
               <span class="label" style="font-family: 'Questrial', sans-serif;"><%= label["name"] %></span>
               <span class="val"><%= label["confidence"].to_i %>%</span>
            </div>
          </div>

      <script type="text/javascript">
        $(document).ready(function() {
          $('.progress-bar').css("width",
            function() {
              return $(this).attr("aria-valuenow") + "%"
            });
        });
      </script>

     </div>
    <% end %>

    <p> Go ahead and upload something else or share this with your friends!</p>
    <div class="fb-share-button" data-href="https://imingle.herokuapp.com" data-layout="box_count" data-size="large" data-mobile-iframe="true"><a class="fb-xfbml-parse-ignore" target="_blank" href="https://imingle.herokuapp.com">Share</a></div>
  <% end %>
  </div>
</div>

<script type="text/javascript">
  (function($){
    $(window).load(function(){
      $(".pmd-card").mCustomScrollbar({
        theme:"rounded-dots-dark",
        scrollInertia:2000
      });
    });
  })(jQuery);

</script>

app/views/photos/create.js.erb
var images_list = $('#images-list');

<% if @photo.save %>
images_list.append('<%= j (render partial: @photo) %>'); 
<% else %>
images_list.html('<%= j (flash_messages)%>').fadeOut(8500);
<% end%>

app/views/photos/edit.html.erb
<%= form_for @photo do |form| %>

<%= render partial: '/photos/form', object: form %>

<% end %>

app/views/photos/index.html.erb
<div class="container-fluid" id="main-header">
	<div class="row">
		<div class="fb-share-button" data-href="https://imageria.herokuapp.com" data-layout="box_count" data-size="large" data-mobile-iframe="true"><a class="fb-xfbml-parse-ignore" target="_blank" href="https://imageria.herokuapp.com">Share</a></div>
	  
	    <div class="page-header jumbotron" style="margin:0 0 30px 0;">

	      <h1 class="animated flipInX"> Welcome to Imageria</h1>
	        <p class="animated fadeIn">Imageria is a simple web app made to demonstrate the image detection and recognition capabilities by machine learning APIs.</p>
	    </div>
	  
	</div>
</div>



<div id="images-list">
	<%= flash_messages %>
</div>


<div class="bg" data-ibg-bg="" style="z-index: -1; width: 50%;height:50%;">
	<div class="row">
		<div class="col-sm-4 col-md-4 col-lg-4"></div>
		<div class="col-sm-8 col-md-8 col-lg-8" style="margin:60px 30px 60px 30px; z-index:99;float:right;">

			<p style="font-size: 25px;">Step 1: Upload a picture</p><p style="font-size: 15px;"> (valid formats: jpg, png, jpeg)</p>
			<%= form_for @photo, remote: true do |form| %>
			  <%= render partial: '/photos/form', object: form %>
			<% end %>
	
	    </div>
	</div>
</div>

<div id="myProgress" class="progress progress-striped active">
    <div class="progress-bar progress-bar-success" id="myBar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%">
    </div>
</div><br>

<div id="analyze" class="bg" data-ibg-bg="assets/upload5.png" style="z-index: -1; width: 40%;height:40%;padding-left: 80px;">
	<div class="row">
		<div class="col-sm-6 col-md-6 col-lg-4"></div>
		<div class="col-sm-6 col-md-6 col-lg-8" style="margin:250px 30px 120px 60px; z-index:99;">

		   
			
	    </div>
	</div>
</div>

app/views/photos/show.html.erb
<div class="container" style="padding-top: 38px">
<div class="row">
  <div class="col-md-6">
<!--    <div class="pmd-card pmd-card-default pmd-z-depth">
    <div class="pmd-card-media"> -->
	    <% if @photo.present? %>
        <%= image_tag @photo.image.url %>
      <% end %>
<!--     </div>
    </div> -->
</div>



<div class="col-md-6">
  <% if @photo.description.present? %>
    <div id="content-1" class="pmd-card pmd-card-default pmd-z-depth pmd-card-custom-form pmd-scrollbar mCustomScrollbar" style="max-height: 600px">
      <div class="pmd-card-title">
      <h3 class="pmd-card-title-text">Image labels</h3>
	    <% @photo.description.each do |label| %>
      <div class="pmd-card-body">
        <!-- <p><%= label["name"] %> <%= label["confidence"].to_i %>%</p> -->
          <div class="progress">
            <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="<%= label["confidence"].to_i %>" aria-valuemin="0" aria-valuemax="100">
               <span class="label"><%= label["name"] %></span>
               <span class="val"><%= label["confidence"].to_i %>%</span>
            </div>
          </div>

      <script type="text/javascript">
        $(document).ready(function() {
          $('.progress-bar').css("width",
            function() {
              return $(this).attr("aria-valuenow") + "%"
            });
        });
      </script>

     </div>
    <% end %>

  <% else %>
	<%= form_tag photos_detect_path, method: :post do %>
	  <%= hidden_field_tag :photo_id, params[:id] %>
  	  <%= submit_tag 'Analyze image', class: "btn pmd-btn-raised pmd-ripple-effect btn-success"%>
  	<% end %>

  <% end %>
  </div>
</div>
</div>

<script type="text/javascript">
  (function($){
    $(window).load(function(){
      $(".pmd-card").mCustomScrollbar({
        theme:"minimal",
        scrollInertia:2000
      });
    });
  })(jQuery);

</script>

</div>